config/routes.rb
Omakase::Application.routes.draw do

  get "/story" => 'home#story'

  get "/contact" => 'home#contact'

  get "/what_is_omakase_box" => 'home#wiob', :as => 'wiob'

  get "/how_it_works" => 'home#hiw', :as => 'hiw'

  get '/fb' => 'home#fb'

	root :to => "subscriptions#new"

	resources :subscriptions, :only => [:create, :new]

  get '/admin_login' => 'sessions#create', :as => :login

 
	

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :email, 
		:uniqueness => true, 
		:presence => true, 
		:length => { :minimum => 3, :maximum => 40 },
		:format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	def admin_signed_in?

		if cookies[:fbs_196091917091198]
			cookie=Hash[cookies[:fbs_196091917091198].gsub('"','').split("&").map{|s| s.split("=")}]
			if cookie["uid"].to_s == ADMIN_1 || cookie["uid"].to_s == ADMIN_2 || cookie["uid"].to_s == ADMIN_3 || cookie["uid"].to_s == ADMIN_4
				return true
			else
				return false
			end
		end

	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def story
  end

  def contact
  end

  def wiob  
  end
 
  def hiw 
  end

  def fb
		 
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
		@subscription = Subscription.new
  end

  def create


#		unless 
Subscription.create!(:email => params[:email])
			#raise Exception 
			#logger.debug "ERROR - Can't create email:" + params[:subscription][:email]
		#end
		
		return
		#flash[:notice] = 'Email Submitted.'
		#redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/home/contact.html.erb
<% content_for :header do %>

	<%= render 'shared/nav' %>

<% end %>

<div id='contact'>


	<h1>Contact</h1>
	<p>Want to get in touch? Ninjas always respond to your emails and tweets.</p>
	<p>Email: <a href='mailto:ninjas@omakasebox.com'>ninjas@omakasebox.com</a></p>

	<p>
		<%= image_tag 'twitter-icon.png',  :id => 'twit-icon-2' %>
		Jing on Twitter: <span id='twit-link1'><%= link_to '@omakase_ninja', 'http://twitter.com/omakase_ninja' %></span>
	</p>

	<p>
		Nancy on Twitter:<span id='twit-link2'>	<%= link_to '@soda_ninja', 'http://twitter.com/soda_ninja' %></span>
	</p>

	<div class='illustrations'>
		<%= image_tag 'contact-ninja.png', :class => 'ninja' %>
		<%= image_tag 'contact-lines.png', :class => 'lines' %>
	</div>


	<div class='filler'>
	</div>

</div>

	<% content_for :footer do %>

		<%= render 'shared/footer' %>

	<% end %>

app/views/home/fb.html.erb
<fb:login-button autologoutlink = true></fb:login-button>

app/views/home/hiw.html.erb
<% content_for :header do %>

	<%= render 'shared/nav' %>

<% end %>

	<div id='how-it-works'>
	<%= image_tag 'hanging_ninja.png', :id=> 'hanging_ninja' %>
	<div class='left'>
		
		<h1>How it Works</h1>
		<div id='search'>

			<div class='img'>
				<%= image_tag 'search.png' %>
			</div>

			<h3>Search</h3>
			
			<p>We're always on the lookout for tasty foods, and with the help of our commu-
			nity of food lovers, we search out the next tasty treat to feature in our monthly
			Omakase box. When we've found something delicious, we'll contact the pro-
			ducer so that we can share the nd with the rest of our community in the next
			delivery of the Omakase box.</p>
		</div>

		<div id='deliver'>

			<div class='img'>
				<%= image_tag 'deliver.png' %>
			</div>

			<h3>Deliver</h3>


			<p>Each month members receive a tasty Omakase box lled with 5-6 food samples
			from our community-driven search. Every box also contains detailed informa-
			tion regarding each product, everything from who made it, how it was made,
			where it came from, and how you can use it. Imagine the anticipation you'll get
			with each delivery!</p>

		</div>


		<div id='share'>

			<div class='img'>
				<%= image_tag 'share.png' %>
			</div>

			<h3>Share</h3>


			<p>We share all our cool nds with our web savvy community by using social
			media tools such as Facebook and Twitter. And they’ll do the same, letting us
			know what they enjoyed in their Omakase box, their own tasty nds, and even
			suggesting things we can feature in next month’s delivery.</p>
		</div>

		<div id='philanthropy'>

			<div class='img'>
				<%= image_tag 'philanthropy.png' %>
			</div>

			<h3>Philanthropy</h3>

			<p>With every Omakase box that's delivered, we donate part of our proceeds to
			Food Banks Canada. As socially conscious foodies, we'll lend a helping hand to
			those less privileged. Hunger is hidden problem in Canada and many don’t
			know that there are a large number of children and families that often go
			hungry before bed. And with the number of people being assisted by a food
			bank on the rise, the urgency has never been greater for those most vulnerable.
			We’d like to do our part, and together, you can still have your cake and share it
			too.</p>

		</div>
	</div>

	<div class='right'>

		<div id='quote'>
			<p class='orange'>“As huge foodies and food consumers, we know first-hand how overwhelming the world of tasty food products can be. Omakase box is designed to be a fun, sociable, and community-driven way to touch, feel, taste, and see food products.</p>

			<p class='orange'>We sort through the clutter to send members what’s good so that they can get it themselves. It’s a fun game everyone can share, with a rewarding treat in the end!”</p>
		</div>
	</div>


	<div class='filler'>
	</div>

</div>

	<% content_for :footer do %>

		<%= render 'shared/footer' %>

	<% end %>

app/views/home/story.html.erb
<% content_for :header do %>

	<%= render 'shared/nav' %>

<% end %>

<div id='story'>



		<div id ='our-story'>

			<div class='left'>

				<h1>Our Story</h1>

				<p>Our two Omakase ninjas met in university and often snuck out of class (like ninjas!) to go out and eat. Student loans were used for food and after graduating, they entered into the pits of the financial industry. Fed up, they quit work and wanted to make polo shirts - they sucked at this.</p>

				<p>One was a soda junkie with an embarrassing attraction to neon green foods while the other was a noodle king and alfajores whore. When they returned from their missions they shared their cool new food finds with their friends just before going off on their next secret mission to find more tasty treats.</p>

				<p>Soon they realized lots of people, like you, wanted to try these tasty finds too.  With foam swords and candy wrapper stars in their dojo our ninjas set out to fulfill their life's mission by finding you awesome foods and delivering them to you in the Omakase box.  There is no telling what our ninjas might bring back next!</p>

			</div>
			
			<div class='right'>

				<%= image_tag 'omakase-story-photo.jpg', :width => '220', :id =>'nancy_jing'%>

				<strong>Secret Mission</strong>
				<p class='orange'>We search high and low, cross oceans and scale mountains, to find the tastiest, weirdest, and coolest bites.  We adhere to the 5-second rule.  We eat everything (sticky or salty, jiggly or firm) and only bring back the good stuff.  We are ninjas.</p>


				(Nancy and Jing pictured above)
			</div>
			
			<div class='spacer'></div>

		</div>

		<div id='a-social-enterprise'>

			<div class='left'>
				
				<%= image_tag 'cake.png', :id => 'cake' %>	
		
			</div>

			<div class='right'>

				<h1>A Social Enterprise</h1>

				<p>We sit on a moral fence between the pleasures of eating and the economic realities of a global food crisis. Even at home, some Canadians are hungry all the time, not to mention the million others worldwide.</p>

				<p>As socially conscious foodies, we'll lend a helping hand to those less privileged. Hunger is hidden problem in Canada and many don’t know that there are a large number of children and families that often go hungry before bed. And with the number of people being assisted by a food bank on the rise, the urgency has never been
				greater for those most vulnerable.</p>

				<p>With every Omakase box that's delivered, we donate part of our proceeds to Food Banks Canada. We’d like to do our part, and together, you can 
				still have your cake and share it too.</p>
			
			</div>
		</div>

	<div class='filler'>
	</div>
</div>

	<% content_for :footer do %>

		<%= render 'shared/footer' %>

	<% end %>

app/views/home/wiob.html.erb
<% content_for :header do %>

	<%= render 'shared/nav' %>

<% end %>


	<div id='what-is-omakase-box'>

		<h1>What is Omakase Box?</h1>

		Omakase box delivers the tasties food treats and food nds to a community of food lovers and a cianados.

		Every month Omakase members will receive a curated selection of food product samples. Each box will span many
		food categories and will deliver exciting new food products that can be eaten right away or used in the prepara-
		tion of their next meal.

		<div class='bottom'>

			<div id='the-box'>

				<h3>THE BOX</h3>

				Each month members receive 5-6 food samples that we’ve tasted and eaten ourselves ranging from snacks, condiments, spices, candies, prepared food, sauces, etc. They can be made by well-known brands to emerging or established artisanal producers.

			</div>

			<div id='the-community'>

				<h3>THE COMMUNITY</h3>

				We’re creating a community of food tasters that search for the coolest, tastiest, and unique new food nds. Once found, the community shares it with us through social media, and we deliver these tasty nds in our next monthly Omakase box to the rest of the community.

			</div>

			<div id='helping-those-in-need'>
				<h3>HELPING THOSE IN NEED</h3>
				Hunger is hidden problem in Canada and many don’t know that there are a large number of children and families that often go hungry before bed. We’d like to do our part. So with every Omakase box that's delivered, we donate part of our proceeds to Food Banks Canada.
			</div>

		</div>

	<%= image_tag 'star_ninja.png', :id => 'star-ninja' %>

<div class='filler'></div>

	</div>

	<% content_for :footer do %>

		<%= render 'shared/footer' %>

	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omakase</title>

<meta name="google-site-verification" content="yLlJOs5HmUhzu5m2pm153bC6aQvpIIgcsRgFmbfseBo" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'rails' %>
  <%= csrf_meta_tag %>
   <link rel="shortcut icon" href="/images/omakase-favicon.ico" >

  <div id="fb-root"><script src="http://connect.facebook.net/en_US/all.js"></script></div>



<script>








	$('#curtain').live('click', function(e) {
		$('#email-success-box').hide();
		$('#email-fail-box').hide();
		$('#curtain').hide();
	});

$(document).ready(function () {

	$('#email-success-box').hide();
	$('#email-fail-box').hide();
	$('#curtain').hide();



	$('#subscription_submit').click(function(e) {

		$.ajax({
			type: 'POST',
			url: '/subscriptions',
			data: {'email':$('#subscription_email').val()},
			success: function() {
				$('#email-success-box').show();
				$('#curtain').show();
				$('#subscription_email').val('');	
			},
			error: function() {
				$('#email-fail-box').show();
				$('#curtain').show();		
				$('#subscription_email').val('');	
			}
			
		});

	});


});

/*
$('#omakase-ninja').live('mouseover mouseout', function(event) {
if (event.type == 'mouseover') {
$('.twitbox1').show();
} else {
$('.twitbox1').hide();

}

});

$('#soda-ninja').live('mouseover mouseout', function(event) {
if (event.type == 'mouseover') {
$('.twitbox2').show();
} else {
$('.twitbox2').hide();

}

});
*/

</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22287546-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>
<div id='container'>

	<%= yield :header %>
	<div id="notice"><%=notice%></div>
	<div class='content'>
		<%= yield %>
	</div>
<div class='spacer'>
</div>
	<%= yield :footer %>
</body>
  <%= javascript_include_tag 'facebook-init' %>
</html>

app/views/shared/_facebook_init.html.erb
<div id="fb-root"><script src="http://connect.facebook.net/en_US/all.js"></script></div>

<script>

	$(document).ready(function () {

	




	});

</script>

app/views/shared/_footer.html.erb
<div id='footer'>
	<div class='content'>
		<%= image_tag 'logo.png', :width => '200', :class=>'logo' %>

		<ul>
			<h2>Navigate</h2>

			<li><%= link_to 'Home', root_url %></li>
			<li><%= link_to 'What is Omakase Box', wiob_url %></li>
			<li><%= link_to 'How it Works', hiw_url %></li>
			<li><%= link_to 'Our Story', story_url %></li>
			<li><%= link_to 'Contact', contact_url %></li>
			<li><%= link_to 'Blog', 'http://blog.omakasebox.com' %></li>
		</ul>


		<ul class='second'>

			<h2>Connect with us</h2>

			<% fb = image_tag 'fb-icon.png', :width=>'40'%>
			<li><%= link_to fb, 'http://www.facebook.com/pages/Omakase-Box/208033962545676' %></li>
			<% twit = image_tag 'twit-icon.png', :width=>'40'%>
			<li><%= link_to twit, 'http://twitter.com/omakase_ninja' %></li>
			<% tumb = image_tag 'tumb-icon.png', :width=>'38'%>
			<li><%= link_to tumb, 'http://blog.omakasebox.com' %></li>
			<% email = image_tag 'email-icon.png', :width=>'38'%>
			<li><%= link_to email, 'mailto:ninjas@omakasebox.com' %></li>

		</ul>

	</div>
</div>

app/views/shared/_home_footer.html.erb
<div id='footer' class='home'>
	<div class='content'>

	<%= image_tag 'logo.png', :width => '200', :class=>'logo' %>

	<ul>

	<h2>Navigate</h2>

		<li><%= link_to 'Home', root_url %></li>
		<li><%= link_to 'What is Omakase Box', wiob_url %></li>
		<li><%= link_to 'How it Works', hiw_url %></li>
		<li><%= link_to 'Our Story', story_url %></li>
		<li><%= link_to 'Contact', contact_url %></li>
		<li><%= link_to 'Blog', 'http://blog.omakasebox.com' %></li>

	</ul>


	<ul class='second'>

		<h2>Connect with us</h2>

		<% fb = image_tag 'fb-icon.png', :width=>'40'%>
		<li><%= link_to fb, root_url %></li>
		<% twit = image_tag 'twit-icon.png', :width=>'40'%>
		<li><%= link_to twit, wiob_url %></li>
		<% tumb = image_tag 'tumb-icon.png', :width=>'38'%>
		<li><%= link_to tumb, hiw_url %></li>
		<% email = image_tag 'email-icon.png', :width=>'38'%>
		<li><%= link_to email, story_url %></li>

	</ul>

	</div>
</div>

app/views/shared/_home_nav.html.erb
<div id='nav' class='home'>

<%= image_tag 'home_link.png', :id => 'home-nav' %>

<div class='links'>
<a href='/how_it_works'><div id="hiw-link"></div></a>
<a href='http://blog.omakasebox.com'><div id="blog-link"></div></a>
<a href='/story'><div id="story-link"></div></a>
<a href='/contact'><div id="contact-link"></div></a>
</div>
</div>

app/views/shared/_nav.html.erb
<div id='nav'>

<%= image_tag 'header.png' %>

<a href='/how_it_works'><div id="hiw-link"></div></a>
<a href='http://blog.omakasebox.com'><div id="blog-link"></div></a>
<a href='/story'><div id="story-link"></div></a>
<a href='/contact'><div id="contact-link"></div></a>


<a href='/'><div id='logo'></div></a>
</div>

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/new.html.erb
<div id='curtain'>
</div>

<%content_for :header do %>
	<%= render 'shared/home_nav' %>
<% end %>

<div class="subscription">

	<div class='top'>

		<%= image_tag 'home_logo.png', :id=>'home-logo'%>

		<div id='fb-like'>
			<fb:like href="http://www.facebook.com/pages/Omakase-Box/208033962545676" layout="button_count" show_faces="true" ></fb:like>
		</div>

		<div id='intro'>
			<h1 id='oh-ma-ka-say'>oh-mah-kah-say</h1> is an expression used at sushi bars to mean leave the selection to the chef.  It is a Japanese phrase that means "it's up to you".  The omakase box is a selection of tasty and unique foods that we handpick and deliver to you.
		</div>

		<div id='two-ninjas'>
			<%= image_tag '2_ninjas.png' %>
			<div class='twitbox1'>
				I'm Jing, find me on Twitter <br/>as <%= link_to '@omakase_ninja', 'http://twitter.com/omakase_ninja'%>
				<%= image_tag 'twitter-icon.png',  :id => 'twit-icon' %> 
			</div>
			<div class='twitbox2'>
				And I'm Nancy, the resident <%= link_to '@soda_ninja', 'http://twitter.com/soda_ninja'%>
			</div>
		</div>
		<div id='omakase-ninja'>
		</div>
		<div id='soda-ninja'>
		</div>

		<div id="signup-box">
			<%= form_for @subscription do |f|%>
				<%= f.label :email, "We'll email you when we launch! No spam, promise."%><br/>
				<%= f.text_field :email%>
				<%# f.submit 'submit'%>
				<a href='#' id='subscription_submit'><div id='submit-wrapper'>submit</div></a>
			<% end %>
		</div>

		<div id='email-success-box'>
			<div class='text'>
				Thanks for signing up!
			</div>
		</div>

		<div id='email-fail-box'>
			<div class='text'>
				Failed to sign up. <br/>Please try again.
			</div>
		</div>

		<div class='spacer'>
		</div>

	</div>


	<div id='what-is-omakase-box'>

		<h1>What is Omakase Box?</h1>

		Omakase box delivers the tasties food treats and food nds to a community of food lovers and a cianados.

		Every month Omakase members will receive a curated selection of food product samples. Each box will span many
		food categories and will deliver exciting new food products that can be eaten right away or used in the prepara-
		tion of their next meal.

		<div class='bottom'>

			<div id='the-box'>

				<h3>THE BOX</h3>

				Each month members receive 5-6 food samples that we’ve tasted and eaten ourselves ranging from snacks, condiments, spices, candies, prepared food, sauces, etc. They can be made by well-known brands to emerging or established artisanal producers.

			</div>

			<div id='the-community'>

				<h3>THE COMMUNITY</h3>

				We’re creating a community of food tasters that search for the coolest, tastiest, and unique new food nds. Once found, the community shares it with us through social media, and we deliver these tasty nds in our next monthly Omakase box to the rest of the community.

			</div>

			<div id='helping-those-in-need'>
				<h3>HELPING THOSE IN NEED</h3>
				Hunger is hidden problem in Canada and many don’t know that there are a large number of children and families that often go hungry before bed. We’d like to do our part. So with every Omakase box that's delivered, we donate part of our proceeds to Food Banks Canada.
			</div>

		</div>

	<%= image_tag 'ninjas.png', :id => 'ninjas' %>

	</div>
	
	
	<% content_for :footer do %>

		<%= render 'shared/home_footer' %>

	<% end %>

</div>